services:
  db:
    image: postgis/postgis:18-3.6
    container_name: farming-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: farming-db
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data:
